#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

test -f $sysresources    && xrdb -merge  $sysresources
test -f $sysmodmap       && xmodmap      $sysmodmap
test -f "$userresources" && xrdb -merge "$userresources"
test -f "$usermodmap"    && xmodmap     "$usermodmap"

# start some nice programs
eval $(ssh-agent)
test $(which gpg-agent) && eval $(gpg-agent --daemon)
test $(which sb) && sb &

# Configure mouse buttons for M570 trackball
xinput --set-button-map 8 1 2 3 4 5 6 7 8 2 &

# set wallpaper or fallback to decent color
test $(which feh) && eval $(feh --bg-center ~/.wallpaper.png) || xsetroot -solid whitesmoke &

if [ $(which xbanish) ]; then
    xbanish >>$HOME/.xbanish.log &    # https://github.com/jcs/xbanish
elif [ $(which unclutter) ]; then
    unclutter &
fi

# source machine- and uname-specific xinitrcs
xinitcfg="$HOME/.config/xinit"
test -f "$xinitcfg/u/$(uname)"       && . "$xinitcfg/u/$(uname)"
test -f "$xinitcfg/host/$(hostname)" && . "$xinitcfg/host/$(hostname)"

/bin/dbus-run-session /usr/local/bin/dwm 2>>.dwm_log
